### ISSUE TITLE
Is water wet? 💧

### ISSUE THREAD

**Issue by samuelsandoval1** [EthanThatOneKid/ama#1]
💦

**Comment by EthanThatOneKid** [comment]
It depends on the definitions of `water` and `wet` in the proposition: `water is wet`.

Let's assume to be `wet` means to be surrounded by an amount of H<sub>2</sub>O chemicals.

If `water` is referring to a single chemical of H<sub>2</sub>O, then the proposition is **false**, it is not wet because it is alone. However, if `water` is referring to an amount of water, then the proposition is **true**; it is inherently surrounded by other H<sub>2</sub>O chemicals.
